version: '3.8'
services:
  mysqldb:
  container_name: mysqldb
  imsge: mysql
  ports:
    - "3306":"3306"
  environment:
    MYSQL_DATABASE: mydb
    MYSQL_ROOT_PASSWORD: ROOT
  webapp:
    container_name: springboot
    build:
      context: ./